export const REQUEST_SENT = "REQUEST_SENT";

export const GET_USER = "GET_USER";
export const SET_USER = "SET_USER";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILED = "REGISTERED_FAILED";
export const LOGOUT = "LOGOUT";

export const USER_DETAILS_SUCCESS = "USER_DETAILS_SUCCESS";
export const USER_DETAILS_FAILED = "USER_DETAILS_FAILED";
export const CLEAR_USER_DETAILS_FROM_STORAGE = 'CLEAR_USER_DETAILS_FROM_STORAGE'

export const GET_USERS_POSTS = "GET_USERS_POSTS";
export const GET_USERS_LIKED_POSTS = "GET_USERS_LIKED_POSTS";

export const GET_FOLLOWERS = 'GET_FOLLOWERS';
export const GET_FOLLOWING = 'GET_FOLLOWING';
export const FOLLOW = 'FOLLOW';
export const UNFOLLOW = 'UNFOLLOW';

